### ISSUE TITLE
Bug: `min-children: 5` enables when there are 4 children

### ISSUE THREAD

**Issue by vegardlarsen** [eqcss/eqcss#16]
Can easily be reproduced by using the min-children sample on the homepage.

![image](https://cloud.githubusercontent.com/assets/436508/16150472/a977cfc4-3497-11e6-8b1e-7ea1a00a8b54.png)

**Comment by tomhodgins** [comment]
Thanks for the bug report - this is clearly my messing up the demo and not a problem with the library - in the meantime here's a more recent version of the same demo you can play around with in Codepen while I fix the main site: http://codepen.io/tomhodgins/pen/dXGoMZ

Also, if you'd like a slimmed down version of the same tests, I've been using this file to test new releases in Firefox that might be nicer to use than the site: http://staticresource.com/fftest.html

Now let me see what's happening on the main site :D

**Comment by tomhodgins** [comment]
We are good on this now ➼ http://elementqueries.com/#min-children

**Comment by vegardlarsen** [comment]
Awesome. That was a quick fix. :)

**Comment by tomhodgins** [comment]
Past-me had put a `<br>` inside those demos for some reason…so they were starting with 1 child already before images were added. With the `<br>` removed, suddenly it’s working as ‘eqcsspected’ again :)

Happy hacking!
