### ISSUE TITLE
Cross origin Issues on demos

### ISSUE THREAD

**Issue by outsmart** [eqcss/eqcss#17]
In some of your demons such as  scroll based blocker I am seeing the demo fail with XMLHttpRequest cannot load with cross origin access control issues
![screenshot 2016-06-18 07 44 27](https://cloud.githubusercontent.com/assets/3925723/16167518/91cc5a98-3528-11e6-8cd3-7ec5e000dad2.png)

http://staticresource.s3.amazonaws.com/template/css/basic.css. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://elementqueries.com' is therefore not allowed access.

**Comment by tomhodgins** [comment]
Hey thanks for pointing this out! I've updated my bucket permissions on Amazon S3 (where those CSS files are hosted) and it looks all good now!

Thanks :)
