### ISSUE TITLE
What about SEO?

### ISSUE THREAD

**Issue by jenstornell** [eqcss/eqcss#18]
Google and probably other search engines are looking not just at the content, but at the layout as well to figure out where the content is places.

How does this affect SEO? Have anyone tried to see how Google sees the site in this tool for example?

https://developers.google.com/speed/pagespeed/insights/

The tool shows a screenshot of your site after generation.

**Comment by tomhodgins** [comment]
That is a great question that I'm not sure I have an expert answer for. When I look up pages built with EQCSS in SEO tools, like the PageSpeed Insights tool, they show up rendered (with JS-powered styles applied) which makes me think for those algorithms that take measurements it would happen after EQCSS had done its thing. Here's an example of an SEO tool showing a page with EQCSS applied: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Felementqueries.com%2Fdemos%2Fcontent-blocks.html

My non-expert guess would be that it would affect web crawlers in a similar way to how adding a JS-powered carousel to a site would affect crawling. In both of those cases, you're putting the content you want visible in your HTML (which could look weird unstyled) and relying on JavaScript to alter the visual display of that markup.

Google can crawl and index JavaScript-powered Single Page Applications and web apps, so I think although EQCSS is an 'unknown' tool at this point for most site analysis tools, I don't believe it has a detrimental effect on how crawlers are able to access and index your content.

Also, EQCSS demos and elementqueries.com have been doing just fine in Google's index, so anecdotally using EQCSS seems to be okay :)
