### ISSUE TITLE
Selectors with :hover and other pseudo-classes

### ISSUE THREAD

**Issue by Velenir** [eqcss/eqcss#24]
Elements with pseudo-classes in their selectors are largely ignored in `EQCSS.apply`. Except when state change(such as with `:checked` on click) also triggers `apply` or `throttle` call, or when an element is static(:first-child).
Is support for pseudo-classes planned somewhere down the line? It could be achieve by attaching event listeners to `mouseenter/mouseleave` to elements with `:hover` etc.
For example something like this: [codepen](http://codepen.io/Velenir/pen/zBRXEP).

**Comment by tomhodgins** [comment]
Hi @Velenir! :D

This looks nice. This sort of functionality is something we've talked about a lot, I'll have Maxime have a look at what you've done here and see whether it's a usable approach for us - thanks for sharing!

**Comment by Velenir** [comment]
The immediate drawback you will see in my approach is that it adds a `cleanup` step before each `apply` -- on one hand it allows to remove `data-eqcss-*` from elements that no longer match selectors (`:hover` is an obvious one, but also dynamically added/removed classes), on the other hand it takes time proportionate to `matched elements X data-eqcss-* attributes on each`. But that time can be considerably shortened if the form of attributes were to be changed, which, granted, would be a rather fundamental modification.
What I have in mind is:
1. Instead of multiple `data-eqcss-*` attributes have one `data-eqcss="0-0 1-1-parent 2-0-prev"` reflecting all relationships
2. Then instead of `[data-eqcss-0-0] {}` css rules would look like `[data-eqcss~="0-0"] {}`
3. All elements with attributes could be chosen with one query `document.querySelectorAll("[data-eqcss]")`
4. And have their attributes removed with one `for(*) element.removeAttribute("data-eqcss")`

Further optimization could be achieved by changing `EQCSS.apply` to accept an element to recalculate states/attributes/test conditions on that element only. Would still be necessary to ensure that attribute numbers are always unique across all incremental `EQCSS.apply(element)` calls. Something like a counter(just take the last `i` from the loop inside `apply`) that gets incremented in `apply(element)` and reset in `apply()`.
I see that you already have this planned for future development.

**Comment by tomhodgins** [comment]
Getting to a spot where I can properly review this and figure out how to best implement it! Thank you very much for your input and for linking this in here @Velenir :D

**Comment by tomhodgins** [comment]
Hey @Velenir! I recently added a cleanup function to EQCSS called `EQCSS.reset()`, do you think that could help accomplish what you're talking about here?

Now that I've written the cleanup function I think it might be efficient to use if you are adding or removing elements to the page (as the order of the attributes might be different). Usually if you are appending new siblings to elements on the page after existing elements it's okay, but if you're changing the order of elements, or prepending siblings you'd want to run `EQCSS.reset()` to clean up and then `EQCSS.load()` to reload EQCSS and write new attributes.

This could be done every once in a while, but I don't think it would run fast enough to be something that could be run every time EQCSS recalculates.

Anyway, just wanted to let you know that was in EQCSS now to see what we can come up with :D
