### ISSUE TITLE
A question on implementation efficiency / eqcss efficiency

### ISSUE THREAD

**Issue by davecranwell** [eqcss/eqcss#25]
For the past couple of years I've taken to a BEM architecture, written in SASS, using nested media queries e.g 

``` sass
.widget {
    padding: 10px;

    @media screen and (min-width: 480px) {
        padding: 20px;
    }

    @media screen and (min-width: 800px) {
        padding: 40px;
    }

    &__title {
         font-size: 12px;

        @media screen and (min-width: 480px) {
            font-size: 14px;
        }

        @media screen and (min-width: 800px) {
            padding: 16px;
        }    
    }
}
```

I've found that in dev teams, particular with a rotating percentage of unfamiliar developers, this kind of nesting is favourable to leaving all the `@media` queries till the bottom of the file (or putting them in an entirely separate file) since mistakes creep in when functionality is too separated/hidden. (Gzipping makes the repetition of the `@media` selectors a negligible cost.)

I was hoping to achieve something like this using EQCSS too, using the following SCSS example:

``` sass
@mixin eq($selector, $condition) {
    @element '#{$selector}' and (#{$condition}) {
        @content;
    }
}

.widget {
     padding: 10px;

    @include eq(&, "min-width: 480px") {
        padding: 20px;
    }

     @include eq(&, "min-width: 800px") {
        padding: 40px;
    }

    // etc
}
```

... however every use of `@element` results in a new `data-eqcss-foo` variable added to `.widget`. I'm a little unclear what these data attrs are for, but my assumption is that the more there are, the more computation is attached to the element. Is this the case?

In which case, could there be an optimisation possible whereby `@element` instances with identical `selector` and `condition` requirements are merged into a single `data` attribute? 

Or am I going about this all wrong?

**Comment by tomhodgins** [comment]
Hi @davecranwell! You're correct in guessing that the data attributes are there during processing and are what the plugin uses to grab onto the elements. For a technical breakdown of how the plugin functions, check out Maxime's [technical documentation for version 1.0.0](http://elementqueries.com/notes/technical-documentation.html)

For structuring my styles I would try to break apart my design into different modules or components, and then write styles for that module with responsive queries for that element right below it:

```
…

/*  sidebar styles */
sidebar CSS
sidebar @element queries

/* footer styles */
footer CSS
footer @element queries

…
```

For your last example, here's how I would structure the same code:

```
.widget {
  padding: 10px;
}
@element '.widget' and (min-width: 480px) {
  $this {
    padding: 20px;
  }
}
@element '.widget' and (min-width: 800px) {
  $this {
    padding: 40px;
  }
}
```

**Comment by davecranwell** [comment]
Thanks for the doc link, that explains a lot. 

So on my page i've got 8 instances of my `.widget`. In each instance,  as in my first example, I'm using `@element` to alter both the top level `.widget` element, and several child `.widget__foo` elements. 

Just 8 instances, each with ~4 `@element`-modified rules, results in the following code:

![screen shot 2016-07-20 at 13 57 50](https://cloud.githubusercontent.com/assets/352835/16987051/ff52ba68-4e81-11e6-9180-36c3356a35ad.png)

Is this expected? At face value that looks rather "wet", and I'm intrigued how it impacts performance.

**Comment by tomhodgins** [comment]
Hi Dave, Can you show the EQCSS code you're running? If you have a `.widget` with a `.title` inside of that you could do something like this:

```
.widget {
}
.widget .title {
}

@element '.widget' and (min-width: 400px) {
  $this {
  }
  $this .title {
  }
}
```

**Comment by davecranwell** [comment]
Yes, defining overrides for several rules within one `@element{}` does indeed reduce the markup considerably. 

However my goal from my original post, is to avoid deferring and clustering the overrides in a single `@element` at the bottom of the component/file. My goal is to have the `@element` overrides for each rule - and **only** that rule (single-responsibility principal and all that) - immediately adjacent to the the rule itself.

So taking your example immediately above, what I'd like is this:

``` css
.widget {
  // imagine lots of lines here, even more if this were using SASS's nesting feature
}
@element '.widget' {
  $this {
  }
}

.widget .title {
}
@element '.widget' {
  $this .title {
  }
}

```

It means you can immediately see what properties of a rule will change at every supported `@element` query, rather than having to scroll up and down a file constantly to compare against the large, complicated `@element` block at the bottom.

 It seems this isn't possible without bloating the `<head>` with loads of inline style tags.

It would be nice if the parser recorded the unique variants of `@element selector_list [ condition_list ]` then _combined_ the `{ css_code}` within each of multiple identical declarations into a single `<style>` tag

**Comment by Velenir** [comment]
I think there is really no need to add its own style tag for each element with `data-eqcss-*-*` as all currently applicable styles are recalculated during `EQCSS.apply` conditions testing and individual rules are unique and based on attributes anyway. Just one `<style data-eqss-read="true">` with everything in it, repopulated at the end of each `EQCSS.apply`.
Like [this](http://codepen.io/Velenir/pen/mExZYj).

**Comment by tomhodgins** [comment]
Definitely interesting ideas @davecranwell and @Velenir, I'm going to see if we can consolidate things into one style tag. Hopefully in the future Houdini will provide a better way to get the CSS applied to the elements that repopulating a tag like this!
