### ISSUE TITLE
Error with attribute selector

### ISSUE THREAD

**Issue by sntran** [eqcss/eqcss#27]
EQCSS seems to choke with the following attribute selector

`'[class^="col-"]', '[class*=" col"]'`

The error in console is

```
about:srcdoc:30 Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '[class^=' is not a valid selector.
```

I have a demo:

http://elementqueries.com/repl.html#css=JTQwZWxlbWVudCUyNTIwJTI1MjdodG1sJTI1MjclMjUyMCUyNTdCJTI1MEElMjUyMCUyNTIwJTI1MjR0aGlzJTI1MjAlMjU3QiUyNTBBJTI1MjAlMjUyMCUyNTIwJTI1MjBiYWNrZ3JvdW5kJTI1M0ElMjUyMHBvd2RlcmJsdWUlMjUzQiUyNTBBJTI1MjAlMjUyMCUyNTdEJTI1MEElMjU3RCUyNTBBJTQwZWxlbWVudCUyNTIwJTI1MjdwJTI1MjclMjUyMGFuZCUyNTIwJTI1MjhtaW4tY2hhcmFjdGVycyUyNTNBJTI1MjAzMCUyNTI5JTI1N0IlMjUwQSUyNTIwJTI1MjAlMjUyNHRoaXMlMjUyMCUyNTdCJTI1MEElMjUyMCUyNTIwJTI1MjAlMjUyMGZvbnQtd2VpZ2h0JTI1M0ElMjUyMGJvbGQlMjUzQiUyNTBBJTI1MjAlMjUyMCUyNTdEJTI1MEElMjU3RCUyNTBBJTI1MEElNDBlbGVtZW50JTI1MjAlMjUyNyUyNTVCY2xhc3MlMjU1RSUyNTNEJTI1MjJjb2wtJTI1MjIlMjU1RCUyNTI3JTI1MkMlMjUyMCUyNTI3JTI1NUJjbGFzcyolMjUzRCUyNTIyJTI1MjBjb2wlMjUyMiUyNTVEJTI1MjclMjUyMCUyNTdCJTI1MEElMjUyMCUyNTIwYmFja2dyb3VuZC1jb2xvciUyNTNBJTI1MjBibHVlJTI1M0IlMjUwQSUyNTIwJTI1MjAlMjUyNHBhcmVudCUyNTIwJTI1N0IlMjUwQSUyNTIwJTI1MjAlMjUyMCUyNTIwYm9yZGVyJTI1M0ElMjUyMDFweCUyNTIwc29saWQlMjUyMHJlZCUyNTNCJTI1MEElMjUyMCUyNTIwJTI1N0QlMjUwQSUyNTdEhtml=JTI1M0NwJTI1M0VUaGlzJTI1MjBpcyUyNTIwdGhlJTI1MjBFUUNTUyUyNTIwUkVQTC4lMjUzQyUyNTJGcCUyNTNFJTI1MEElMjUwQSUyNTNDcCUyNTNFQmVnaW4lMjUyMGVkaXRpbmclMjUyMHRoaXMlMjUyMGNvZGUlMjUyMGFuZCUyNTIwd2F0Y2glMjUyMHRoZSUyNTIwY2hhbmdlcyUyNTIwaGFwcGVuJTI1MjBsaXZlJTI1MjBpbiUyNTIwdGhlJTI1MjBwcmV2aWV3JTI1MjBwYW5lJTI1RTIlMjU4MCUyNUE2JTI1M0MlMjUyRnAlMjUzRSUyNTBBJTI1MEElMjUzQ2RpdiUyNTIwY2xhc3MlMjUzRCUyNTIyc2hvdWxkLWJlLXBhcmVudCUyNTIyJTI1M0UlMjUwQSUyNTIwJTI1MjAlMjUzQ2RpdiUyNTIwY2xhc3MlMjUzRCUyNTIyY29sLTMlMjUyMiUyNTNFLmNvbC0zJTI1M0MlMjUyRmRpdiUyNTNFJTI1MEElMjUyMCUyNTIwJTI1M0NkaXYlMjUyMGNsYXNzJTI1M0QlMjUyMmFub3RoZXItY2xhc3MlMjUyMGNvbC01JTI1MjIlMjUzRS5jb2wtNSUyNTNDJTI1MkZkaXYlMjUzRSUyNTBBJTI1M0MlMjUyRmRpdiUyNTNFJTI1MEE=

**Comment by tomhodgins** [comment]
Hi @sntran! The formatting for the selectors, and rules inside the element query weren't quite right. I've updated it [to the following](http://elementqueries.com/repl.html#css=JTQwZWxlbWVudCUyNTIwJTI1MjdodG1sJTI1MjclMjUyMCUyNTdCJTI1MEElMjUyMCUyNTIwJTI1MjR0aGlzJTI1MjAlMjU3QiUyNTBBJTI1MjAlMjUyMCUyNTIwJTI1MjBiYWNrZ3JvdW5kJTI1M0ElMjUyMHBvd2RlcmJsdWUlMjUzQiUyNTBBJTI1MjAlMjUyMCUyNTdEJTI1MEElMjU3RCUyNTBBJTQwZWxlbWVudCUyNTIwJTI1MjdwJTI1MjclMjUyMGFuZCUyNTIwJTI1MjhtaW4tY2hhcmFjdGVycyUyNTNBJTI1MjAzMCUyNTI5JTI1N0IlMjUwQSUyNTIwJTI1MjAlMjUyNHRoaXMlMjUyMCUyNTdCJTI1MEElMjUyMCUyNTIwJTI1MjAlMjUyMGZvbnQtd2VpZ2h0JTI1M0ElMjUyMGJvbGQlMjUzQiUyNTBBJTI1MjAlMjUyMCUyNTdEJTI1MEElMjU3RCUyNTBBJTI1MEElNDBlbGVtZW50JTI1MjAlMjUyNyUyNTVCY2xhc3MlMjU1RSUyNTNEY29sLSUyNTVEJTI1MkMlMjUyMCUyNTVCY2xhc3MqJTI1M0Rjb2wlMjU1RCUyNTI3JTI1MjAlMjU3QiUyNTBBJTI1MjAlMjUyMCUyNTI0dGhpcyUyNTIwJTI1N0IlMjUwQSUyNTIwJTI1MjAlMjUyMCUyNTIwYmFja2dyb3VuZC1jb2xvciUyNTNBJTI1MjBibHVlJTI1M0IlMjUwQSUyNTIwJTI1MjAlMjU3RCUyNTBBJTI1MjAlMjUyMCUyNTI0cGFyZW50JTI1MjAlMjU3QiUyNTBBJTI1MjAlMjUyMCUyNTIwJTI1MjBib3JkZXIlMjUzQSUyNTIwMXB4JTI1MjBzb2xpZCUyNTIwcmVkJTI1M0IlMjUwQSUyNTIwJTI1MjAlMjU3RCUyNTBBJTI1N0Q=html=JTI1M0NwJTI1M0VUaGlzJTI1MjBpcyUyNTIwdGhlJTI1MjBFUUNTUyUyNTIwUkVQTC4lMjUzQyUyNTJGcCUyNTNFJTI1MEElMjUwQSUyNTNDcCUyNTNFQmVnaW4lMjUyMGVkaXRpbmclMjUyMHRoaXMlMjUyMGNvZGUlMjUyMGFuZCUyNTIwd2F0Y2glMjUyMHRoZSUyNTIwY2hhbmdlcyUyNTIwaGFwcGVuJTI1MjBsaXZlJTI1MjBpbiUyNTIwdGhlJTI1MjBwcmV2aWV3JTI1MjBwYW5lJTI1RTIlMjU4MCUyNUE2JTI1M0MlMjUyRnAlMjUzRSUyNTBBJTI1MEElMjUzQ2RpdiUyNTIwY2xhc3MlMjUzRCUyNTIyc2hvdWxkLWJlLXBhcmVudCUyNTIyJTI1M0UlMjUwQSUyNTIwJTI1MjAlMjUzQ2RpdiUyNTIwY2xhc3MlMjUzRCUyNTIyY29sLTMlMjUyMiUyNTNFLmNvbC0zJTI1M0MlMjUyRmRpdiUyNTNFJTI1MEElMjUyMCUyNTIwJTI1M0NkaXYlMjUyMGNsYXNzJTI1M0QlMjUyMmFub3RoZXItY2xhc3MlMjUyMGNvbC01JTI1MjIlMjUzRS5jb2wtNSUyNTNDJTI1MkZkaXYlMjUzRSUyNTBBJTI1M0MlMjUyRmRpdiUyNTNFJTI1MEE=):

``` css
@element '[class^=col-], [class*=col]' {
  $this {
    background-color: blue;
  }
  $parent {
    border: 1px solid red;
  }
}
```

The changes you'll notice are that:
- both selectors are wrapped by a pair of quotes and separated by a comma
- the `background-color: blue;` property is wrapped in a rule that applies it to `$this`, which is any element on the page matching the query.

I believe this looks like what you're after :)

![repl](https://cloud.githubusercontent.com/assets/955601/17178955/6aff1668-53e5-11e6-8d1e-0e0865e47d26.png)

**Comment by sntran** [comment]
Hi @tomhodgins,

For some reason, I can't see your comment, if any. I just see you closing the issue without any comment.

**EDIT BY @TOMHODGINS** Yeah sorry, there's something goin on with my Github account right now, I've contacted support. Here's what I tried to write:

> Hi @sntran! The formatting for the selectors, and rules inside the element query weren't quite right. I've updated it [to the following](http://elementqueries.com/repl.html#css=JTQwZWxlbWVudCUyNTIwJTI1MjdodG1sJTI1MjclMjUyMCUyNTdCJTI1MEElMjUyMCUyNTIwJTI1MjR0aGlzJTI1MjAlMjU3QiUyNTBBJTI1MjAlMjUyMCUyNTIwJTI1MjBiYWNrZ3JvdW5kJTI1M0ElMjUyMHBvd2RlcmJsdWUlMjUzQiUyNTBBJTI1MjAlMjUyMCUyNTdEJTI1MEElMjU3RCUyNTBBJTQwZWxlbWVudCUyNTIwJTI1MjdwJTI1MjclMjUyMGFuZCUyNTIwJTI1MjhtaW4tY2hhcmFjdGVycyUyNTNBJTI1MjAzMCUyNTI5JTI1N0IlMjUwQSUyNTIwJTI1MjAlMjUyNHRoaXMlMjUyMCUyNTdCJTI1MEElMjUyMCUyNTIwJTI1MjAlMjUyMGZvbnQtd2VpZ2h0JTI1M0ElMjUyMGJvbGQlMjUzQiUyNTBBJTI1MjAlMjUyMCUyNTdEJTI1MEElMjU3RCUyNTBBJTI1MEElNDBlbGVtZW50JTI1MjAlMjUyNyUyNTVCY2xhc3MlMjU1RSUyNTNEY29sLSUyNTVEJTI1MkMlMjUyMCUyNTVCY2xhc3MqJTI1M0Rjb2wlMjU1RCUyNTI3JTI1MjAlMjU3QiUyNTBBJTI1MjAlMjUyMCUyNTI0dGhpcyUyNTIwJTI1N0IlMjUwQSUyNTIwJTI1MjAlMjUyMCUyNTIwYmFja2dyb3VuZC1jb2xvciUyNTNBJTI1MjBibHVlJTI1M0IlMjUwQSUyNTIwJTI1MjAlMjU3RCUyNTBBJTI1MjAlMjUyMCUyNTI0cGFyZW50JTI1MjAlMjU3QiUyNTBBJTI1MjAlMjUyMCUyNTIwJTI1MjBib3JkZXIlMjUzQSUyNTIwMXB4JTI1MjBzb2xpZCUyNTIwcmVkJTI1M0IlMjUwQSUyNTIwJTI1MjAlMjU3RCUyNTBBJTI1N0Q=html=JTI1M0NwJTI1M0VUaGlzJTI1MjBpcyUyNTIwdGhlJTI1MjBFUUNTUyUyNTIwUkVQTC4lMjUzQyUyNTJGcCUyNTNFJTI1MEElMjUwQSUyNTNDcCUyNTNFQmVnaW4lMjUyMGVkaXRpbmclMjUyMHRoaXMlMjUyMGNvZGUlMjUyMGFuZCUyNTIwd2F0Y2glMjUyMHRoZSUyNTIwY2hhbmdlcyUyNTIwaGFwcGVuJTI1MjBsaXZlJTI1MjBpbiUyNTIwdGhlJTI1MjBwcmV2aWV3JTI1MjBwYW5lJTI1RTIlMjU4MCUyNUE2JTI1M0MlMjUyRnAlMjUzRSUyNTBBJTI1MEElMjUzQ2RpdiUyNTIwY2xhc3MlMjUzRCUyNTIyc2hvdWxkLWJlLXBhcmVudCUyNTIyJTI1M0UlMjUwQSUyNTIwJTI1MjAlMjUzQ2RpdiUyNTIwY2xhc3MlMjUzRCUyNTIyY29sLTMlMjUyMiUyNTNFLmNvbC0zJTI1M0MlMjUyRmRpdiUyNTNFJTI1MEElMjUyMCUyNTIwJTI1M0NkaXYlMjUyMGNsYXNzJTI1M0QlMjUyMmFub3RoZXItY2xhc3MlMjUyMGNvbC01JTI1MjIlMjUzRS5jb2wtNSUyNTNDJTI1MkZkaXYlMjUzRSUyNTBBJTI1M0MlMjUyRmRpdiUyNTNFJTI1MEE=):
> 
> ``` css
> @element '[class^=col-], [class*=col]' {
>   $this {
>     background-color: blue;
>   }
>   $parent {
>     border: 1px solid red;
>   }
> }
> ```
> 
> The changes you'll notice are that:
> - both selectors are wrapped by a pair of quotes and separated by a comma
> - the background-color: blue; property is wrapped in a rule that applies it to $this, which is any element on the page matching the query.
> 
> I believe this looks like what you're after :)
> ![](https://cloud.githubusercontent.com/assets/955601/17178955/6aff1668-53e5-11e6-8d1e-0e0865e47d26.png)

**Comment by sntran** [comment]
Thank you, that worked. Hope your issue with Github is sorted out :)

**EDIT BY @TOMHODGINS** Thanks! Hope you have a great day and have fun experimenting with EQCSS ^^ If you have any other questions feel free to hop into our chat at https://gitter.im/eqcss/eqcss any time!
