### ISSUE TITLE
Problems with CDN, other issues

### ISSUE THREAD

**Issue by timothyjoh** [eqcss/eqcss#28]
So, one problem we discovered a bit too late with EQCSS is that when we have CSS files loaded to a CDN in production, the CDN doesn't permit EQCSS to load in the files via AJAX load. So the automatic loading of every CSS file linked in the document with a < link > tag is something we need to change. I like the fact that we have multiple ways we can put the EQCSS in the document, in a script tag, or in the actual CSS files themselves, but this last method isn't documented on your site and was a surprise to us until reading the code. 

Also because of this, on a site where our CSS is not all concatenated (a wordpress site with custom theme installed) this means that 30+ css files are loading again, which is overkill.

I recommend that we either take out this undocumented "feature" or put some kind of rule on it that it only Ajax loads documents with an href ending in ".eqcss" or some other attribute match, instead of reloading all CSS. Does this make sense, or am I missing something vital?

**Comment by timothyjoh** [comment]
#29 I created this PR for you to consider. Solves my current needs by limiting the amount of needless Ajax calls to CSS files.

**Comment by tomhodgins** [comment]
Hey @jhnsntmthy, thanks for opening this issue. I've commented in the PR so I'll quote that here:

>I don't think we should restrict EQCSS to only loading files with the string eqcss in the filename because that would break what's already out there, but also because you could have something like reqcss.css or some other name that would wrongly trigger this.
>
> If you want to have EQCSS ignore fetching a stylesheet via <link> or <script type=text/eqcss> you should be able to add the data-eqcss-read=true attribute to the tag yourself in HTML and it should be ignored by EQCSS.

Let me know if this works for you :D
