### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by xem** [eqcss/eqcss#3]
Pick from this list for future versions
(from https://docs.google.com/spreadsheets/d/1zzjFSjpVog1FIflN0mQe1RBQ0B10o-nlyJyK4etXJcE/edit#gid=0)
- [x] make var work with the current element's scope
- [x] make var() work outside of EQCSS code (in regular CSS)
- [ ]  handle new eqcss code added dynamically after page load
- [ ]  JS-like comments
- [ ]  handle min-lines queries on textareas
- [ ]  handle max-lines queries on textareas
- [ ]  min-font-size in px
- [ ]  max-font-size in px
- [ ]  max-width: $native-width; max-height: $native-height
- [ ]  min-padding-top, min-margin-top, min-border-top-width, etc etc etc
- [ ]  execute element queries automatically when the DOM changes
- [ ]  content: computed_css_property(xyz);
- [ ]  add a input[type="textish"] 
- [ ]  add a input[type="buttonish"] 
- [ ]  add a input[type="checkish"] 
- [ ]  add a input[type="pickish"] 
- [ ]  add an attribute setter
- [ ]  eqcss variables 
- [ ]  set scroll in css/eqcss rules
- [ ]  html content
- [ ]  define multiple equal properties at once
- [ ]  $naturalOffsetTop and $naturalOffsetLeft
- [x]  $prev keyword selects previous sibling (no matter the tag)
- [x]  $next keyword select next sibling (no matter the tag)

**Comment by tomhodgins** [comment]
I think two separate features we have wanted: multiple elements per query, as well as groups of elements (like `[type=textish]` or `[type=buttonish]`) can (and should) actually be expressed as a CSS function, perhaps named `group()`.

Here's an example of two things that are currently annoying to do in CSS/EQCSS:
- same query for multiple elements:

```
@element 'div' and (min-characters: 50) {
  $this {
    color: red;
  }
}
@element 'span' and (min-characters: 50) {
  $this {
    color: red;
  }
}
```

But also when you want to express a number of possible elements:

```
h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: 'Comic Sans';
}
```

But that's not super obnoxious, where it gets annoying is when you want to use a '+' selector, like this:

```
h1 + h1,
h1 + h2,
h1 + h3,
h1 + h4,
h1 + h5,
h1 + h6,
h2 + h1,
h2 + h2,
h2 + h3,
h2 + h4,
h2 + h5,
h2 + h6,
h3 + h1,
h3 + h2,
h3 + h3,
h3 + h4,
h3 + h5,
h3 + h6,
h4 + h1,
h4 + h2,
h4 + h3,
h4 + h4,
h4 + h5,
h4 + h6,
h5 + h1,
h5 + h2,
h5 + h3,
h5 + h4,
h5 + h5,
h5 + h6,
h6 + h1,
h6 + h2,
h6 + h3,
h6 + h4,
h6 + h5,
h6 + h6 {
  margin-top: 0;
}
```

Or perhaps you did something to `p`, `ul`, and `ol`, and then you want to control when they follow each other:

```
p + p,
p + ul,
p + ol,
ol + p,
ol + ul,
ol + ol,
ul + p,
ul + ol,
ul + ul {
  margin-top: 1em;
}
```

What if these could be expressed like this:

```
@element 'group(div,span)' and (min-characters: 50) {
  $this {
    color: red;
  }
}
```

```
group(h1,h2,h3,h4,h5,h6) + group(h1,h2,h3,h4,h5,h6) {
  margin-top: 0;
}
```

```
group(p,ol,ul) + group(p,ol,ul) {
  margin-top: 1em;
}
```

What do you think? This means stuff like `[type=textish]` would be something like:

```
group([type=text],[type=url],[type=date],[type=password],[type=email],[type=tel]) etc.
```

and the button one could look like this:

```
group(.button,button,[type=button],[type=submit])
```

**Comment by xem** [comment]
That's a very nice idea. Not the easiest onr to implement, but nice. :)

**Comment by tomhodgins** [comment]
Indeed - sometimes it would require duplicating queries, sometimes it would mean duplicating rules, and sometimes it would mean both

**Comment by JawsomeJason** [comment]
@xem, I just wrote an [EQCSS Sass Mixin](https://gist.github.com/thejase/d2107285b6e10315dd6bc055115647fe) that might assist.  Essentially:

``` scss
p, ol, ul {
  & + & {
    @include element((min-characters: 50)) {
      eq_this {
        color: red;
      }
    }
  }
}

/* Output:
@element 'p + p, ol + p, ul + p, p + ol, ol + ol, ul + ol, p + ul, ol + ul, ul + ul' and (min-characters: 50) {
  eq_this {
    color: red;
  }
}
*/
```

If you happen to use that preprocessor, hope this might help with your annoyance.

**Comment by tomhodgins** [comment]
Hi @thejase, Thanks for the snippet! I've experimented with a similar idea outside of using preprocessors with just CSS + JS (using EQCSS). Here's an example where I saved lists of selectors as strings and used them inside my CSS as variables (with the ability to modify what gets returned, with `:hover` or other modifications applied: http://codepen.io/tomhodgins/pen/KgwVOR

I'm not a big SASS user myself, but I'll see if I can get your `@element` mixin working in a demo on Codepen - when we re-do the element queries website I think there will be a new section for SASS, PostCSS, Stylus, etc and ways to use the syntax with those tools as well that should have snippets like this in it!

**Comment by JawsomeJason** [comment]
`[type="textish"]`, etc. is very fascinating!  I like this idea from a non-preprocessor perspective, no doubt!  If/when you go that route, it'd be nice to be able to define custom "-ishes."  Playing devil's advocate, at that point, one might consider moving to a pre-processor anyway.  

Although EQCSS (by its nature) doesn't adhere to this assertion, I prefer my end-CSS to be as plain as possible.  For me, the `@element 'p + p, ol + p...'` is easy to debug and comprehend because of it's explicitness, whereas `@element '[type=textish]'` makes me have to think/research as to what that to what that will apply.  Plus, if EQCSS `eval()` sets get updated in a revision, it may change my site inadvertently.  

On a similar note, it would be nice to see an inline comment in each generated style as to what `@element` is applying it.

**Comment by tomhodgins** [comment]
You can already use the stuff from that demo anywhere in EQCSS! What I did was define a bunch of strings that were valid CSS selectors, and then anywhere inside an `@element` query I am able to use `eval("")` to evaluate any JavaScript value on the page. In this demo I've added two tags to the HTML: div, and span. And in my JS I've defined a variable with the value `tags = 'div,span'`. I can use this in any element query, in this case I used `eval("tags")` so when I do

```
eval("tags") {}
```

It will output this in the final CSS:

```
div,span {}
```

Here's the demo code:

```
<div>div</div>
<span>span</span>
<style>
  @element 'html' {
    eval('tags') {
      padding: 2em;
      background: red;
    }
  }
</style>
<script>
  var tags = 'div,span'
</script>
<script src=http:/elementqueries.com/EQCSS.js></script>
```

Try using this link to open it as a page -> Not sure if Github will strip the link or not: [Demo link](data:text/html,<div>div</div><span>span</span><style>@element'html'{eval%28'tags'%29{padding:2em;background:red}}</style><script>var tags='div,span'</script><script src=http:/elementqueries.com/EQCSS.js></script)

Edit: it did strip it, it was simply appending: `data:text/html,` above the demo code so it would load as a web page...

**Comment by JawsomeJason** [comment]
Indeed it did strip it.  My apologies on the "if/when."  I misread and thought the codepen link was an _upcoming_ feature.

**Comment by xem** [comment]
what happened?

**Comment by tomhodgins** [comment]
Oh I was closing this because it's not really an 'issue' per se. I mostly come here to look at your list in the [first comment](https://github.com/eqcss/eqcss/issues/3#issue-120492269) so I'm closing this and other non-issue issues so we can keep issues clear for open issues. We'll still be able to reference this in the 'closed issues' area forever :D
