### ISSUE TITLE
IE11/Edge13 Bug

### ISSUE THREAD

**Issue by shaekuronen** [eqcss/eqcss#31]
Getting these errors in IE11 & Edge 13. Eliminated instance where we were calling an EQCSS method directly, so it seems like the bug is w/ EQCSS. However, on http://elementqueries.com/ am not seeing the same bug, so maybe it's an interaction w/ another library.

Anyway, has anyone encountered this bug before?

![screen shot 2016-08-12 at 1 59 47 pm](https://cloud.githubusercontent.com/assets/537283/17636926/37075778-6095-11e6-9180-065228e4d316.png)

![screen shot 2016-08-12 at 12 53 48 pm](https://cloud.githubusercontent.com/assets/537283/17636933/3cc035ae-6095-11e6-9ed7-c94a1fa10e0c.png)

**Comment by tomhodgins** [comment]
Hi @shaekuronen! I haven't seen that error before, I'll check some of the EQCSS demos in those browsers to see if I can reproduce it.

Do you have a link to where you're seeing the error, or are you able to create a test case with the libraries you're using where the error you see happens?

Thanks so much for noticing this, and letting us know :D

**Comment by shaekuronen** [comment]
Client work, I think I have to have an NDA in place to show it :/ 

I'll put together a simple test case

**Comment by tomhodgins** [comment]
:S I dont like NDAs, but I do like reproducible test cases!

I'm curious to see if we can get to the bottom of this, and if it _is_ an interaction with other libraries if there is a way we can protect aginst this with a small change to how we do things

**Comment by shaekuronen** [comment]
The sequence of events is
1. style element with no content `<style data-eqcss-read="true"></style>`
2. in EQCSS.load, `EQCSS.parse(styles[i].innerHTML)` is called
3. because the style element has no innerHTML, it's undefined
4. in EQCSS.parse, the argument isn't type checked
5. in code cleanup, `code = code.replace(/\s+/g," ");` replace is called on undefined, which errors

Not sure what's causing all the empty style tags to be generated by EQCSS

Currently using this in EQCSS.parse to prevent error

```
        EQCSS.parse = function(code){

          console.log('code is ' + code);

          // Cleanup
          code = typeof code === 'string' ? code : ""; // make sure code is a string
          code = code.replace(/\s+/g," "); // reduce spaces and line breaks
          code = code.replace(/\/\*[\w\W]*?\*\//g,""); // remove comments
          code = code.replace(/@element/g,"\n@element"); // one element query per line
          code = code.replace(/(@element.*?\{([^}]*?\{[^}]*?\}[^}]*?)*\}).*/g, "$1"); // Keep the queries only (discard regular css written around them)
```

There's probably a more graceful way to do it, but (as far as I can tell) type checking the input to EQCSS.parse would allow empty eq_this statements w/out throwing an error in IE & Edge. 

Unfortunately, I haven't been able to replicate the bug in a demo project. Any idea what's going on from the above info?

**Comment by shaekuronen** [comment]
Well, hmm, it's gotta be more than just the no content style tag. I have a couple of those being generated by EQCSS in the demo project & the error's not happening.

**Comment by shaekuronen** [comment]
Doesn't duplicate the bug yet, but the demo I've been working on is the sk/eqcss branch of https://github.com/fellswoop/static-project-template

**Comment by shaekuronen** [comment]
Ok, I think I finally figured this out. Using gulp-svgstore to generate inline svgs. The svgs themselves had empty `<defs><style></style></defs>` tags. These tags were getting inlined and a couple of them were broken in terms of opening & closing tags. When I removed the non-conforming html by removing the defs & style tags from the svgs, the issues w/ EQCSS resolved.

**Comment by tomhodgins** [comment]
Glad this got sorted out! I've been playing with SVG in my CSS and having a lot of fun lately too :D
