### ISSUE TITLE
Poll for Changes Independent of Browser Resize

### ISSUE THREAD

**Issue by mcraiganthony** [eqcss/eqcss#32]
This is a feature request.

It would be wonderful to have the option to constantly poll for element changes. Many complex applications implement panel systems - panel slides onto page and squeezes the page's content.

In this case, the width of the page's content is narrowing and I need to apply EQCSS to handle UI changes. Unfortunately, EQCSS won't be applied because there was no browser resize event.

I understand that EQCSS may be called manually when the panel is triggered to open. Calling EQCSS manually will work properly if it's called AFTER the transition is complete (after panel slides onto page and page content is squeezed). This tactic would require that the transitions are implemented using JS. But if transitions are implemented using CSS, it makes it tough to time properly.

Any thoughts / advice would be appreciated. Thanks!

**Comment by acicali** [comment]
One could also add an event listener for "animationend" to trigger eqcss after css animations.

**Comment by tomhodgins** [comment]
Hi @mcraiganthony! I see what you mean about wanting it to wait to execute until the CSS animation completes. Did the idea from @acicali help at all?

Do you have any demo code that illustrates the issue that we can play with and find a fix for?

**Comment by tomhodgins** [comment]
@mcraiganthony! Have you found a workaround/solution to the animation issue? When you say:

> In this case, the width of the page's content is narrowing and I need to apply EQCSS to handle UI changes. Unfortunately, EQCSS won't be applied because there was no browser resize event.

That does make me think of something similar I do. On some element query demos I have a script that will add a little drag handle for touchscreen users so they can drag to resize the demos. This function, (which you can spot at the bottom of http://elementqueries.com) has code like this:

```
document.addEventListener('mouseup',drop)
document.addEventListener('touchend',drop)
…
function drop(e){
  grabbed = undefined
  EQCSS.throttle()
}
```

There are functions that run on `click`/`touchstart` which grab the element, `mousemove`/`touchmove` which resize the element, and then every `mouseup`/`touchend` event I recalculate EQCSS manually with `EQCSS.throttle()`.

You can call `EQCSS.throttle()` as frequently as you want and it will throttle it to running no more frequently than every `200ms`. If you want EQCSS to recalculate instantly (could be performance heavy, depending on how many queries + elements) you can also call `EQCSS.apply()` directly, bypassing the throttle entirely.

It sounds to me like you need to find a way to determine an event JavaScript can listen to on your page that would manually call one of these two functions.

**Comment by mcraiganthony** [comment]
Thanks @tomhodgins I appreciate the insight! It's certainly a tough problem to solve especially when trying to keep performance at an optimal level.

Unfortunately I had to (temporarily) pull EQCSS from my project. I was prototyping in Codepen using LESS and it was working wonderfully for nearly 2 months. Then, about a week ago, Codepen started throwing errors regarding LESS directives. I spent a full day trying to use EQCSS in LESS with no luck. I saw an issue here where someone inquired about using EQCSS in LESS and it was closed without much discussion. I'm going to revisit the issue and see if I can find a way to make it work - at which point I'll gladly share.

**Comment by tomhodgins** [comment]
> I saw an issue here where someone inquired about using EQCSS in LESS and it was closed without much discussion.

In response to a couple of tickets regarding preprocessors, we went ahead and [pushed out an update](https://github.com/eqcss/eqcss/releases/tag/v1.1.1) to make sure EQCSS was working well with [SCSS](http://codepen.io/tomhodgins/pen/XKbamW), [Less](http://codepen.io/tomhodgins/pen/pbpLJX), and [Stylus](http://codepen.io/tomhodgins/pen/AXxPLb).

I'm seeing the same 'directive' thing on Codepen, but I wonder if that's how they have it configured or if they've changed the way Less compilation works over the past couple months. Have you run into the same Directive issue with Less outside of Codepen as well?

You're able to replace any meta-selector in EQCSS that starts with `$` (like `$this`, `$root`, `$parent`, `$next`, or `$prev`) with `eq_`(like `eq_this`, `eq_root`, `eq_parent`, `eq_next`, or `eq_prev`) which seemed to be the biggest issue with preprocessors.

If you have any questions about how to use EQCSS or write element queries, or have code samples you're working on (like on Codepen) feel free to join us in the [Gitter channel](gitter.im/eqcss/eqcss) and we can troubleshoot and figure stuff out together!

**Comment by mcraiganthony** [comment]
@tomhodgins Oh man that's great news! My gut was telling me that it was a Codepen issue since EQCSS worked for a couple of months and then suddenly stopped. I'll let you know if I run into any problems using it outside of Codepen. I appreciate the help!
