### ISSUE TITLE
Any plans to support element queries natively?

### ISSUE THREAD

**Issue by Wildhoney** [eqcss/eqcss#37]
Merely a question.

I've heard a **lot** about element queries over the past couple of years, but there doesn't seem to be a spec lying around that intends to have it supported natively in the browsers. It seems like a huge downside to the whole _everything as a component_ paradigm.

What's the latest? Does it not make sense now we're pushing ahead with webcomponents?

**Comment by tomhodgins** [comment]
Hi @Wildhoney! Thanks for your interest!

There isn't a spec yet, though I'm still trying to stir up excitement to get at least _something_ written down. Here's some emails from the RICG mailing list last month that kind of states where people are at: http://lists.w3.org/Archives/Public/public-respimg/2016Sep/

If I can summarize, some folks are waiting for Houdini to arrive before seeing how that changes things - and expect Houdini polyfills to emerge on their own. Some people want a CSS-like spec that browsers may one day implement, and some people just want a syntax standardized so whether we use compilers, Houdini, or browser implementation we can all be supporting the same syntax.

I would like to see some kind of syntax standardized (no matter the implementation) so hopefully real work can begin on that soon. I'm not sure how/where to get started. Here's my best definition of the EQCSS syntax: https://gist.github.com/tomhodgins/6237039fa07c2e4b7acd1c8b0f9549a9

The cool thing about EQCSS is that even though it does make building self-responsive components vey easy - you don't need to use it in that way. I've had a lot of fun recently doing some weird stuff with EQCSS that has nothing to do with components at all:
- Infinity-shaped animation: http://codepen.io/tomhodgins/pen/wzAGvw
- Colors change based on mouse position: http://codepen.io/tomhodgins/pen/VKrLyN
- CSS Lock / Number Clamp: http://codepen.io/tomhodgins/pen/ALWaVr
- Responsive multi-line truncation: http://codepen.io/tomhodgins/pen/KgKggX

And this video I made yesterday using EQCSS to experiment with what a CSS property like `aspect-ratio` might be like: https://www.youtube.com/watch?v=FcxCGjMNhcg

**Comment by Wildhoney** [comment]
Thanks for this @tomhodgins &ndash; it seems as though you're doing some good work on getting it standardised. I hear you on Houdini though &ndash; exciting times ahead!

I also came across [`ResizeObserver`](https://wicg.github.io/ResizeObserver/) today which seems as though it'd be able to achieve something similar to element queries. I'm interested how Houdini and `ResizeObserver` could work together.

**Comment by scooterlord** [comment]
great job, keep it up!

**Comment by tomhodgins** [comment]
@Wildhoney Yeah, we plan to use everything that's available to us, so as things like resizeObserver and Houdini land we'll be trying to find a forward compatible way to use those instead of our (current) JS which will serve as a fallback for today's browsers (in the future).

Exciting times are coming, but they still feel perpetually 4-5 years away
