### ISSUE TITLE
Error in IE 11 (Windows 8)

### ISSUE THREAD

**Issue by eye8** [eqcss/eqcss#39]
I use EQCSS 1.3.0 with npm and webpack. It's working great in Chrome, FF, and Safari. But I encounter the following error in IE 11 (Windows 8):

```
Object doesn't support property or method 'throttle'
```

This happens because Line 853 calls the `EQCSS.throttle()` function which isn't known to IE 11 so far:

```
EQCSS.domReady(function(){
  EQCSS.load();
  EQCSS.throttle();
});
```

A simple fix (verified) is to move Line 851-854 to after the definition of `EQCSS.throttle  = function() {...}`. 

Our project is on hold due to this error. Please fix it, thank you!

**Comment by tomhodgins** [comment]
Hi @eye8, thanks for trying out EQCSS! I'm testing this in IE11 with EQCSS v1.3.0 and I can't seem to reproduce the error.

Do you see the same error when you load EQCSS outside of your webpack workflow? For example, is the problem still there in IE11 if you use the CDN-hosted version from https://cdnjs.com/libraries/eqcss ?

**Comment by eye8** [comment]
Hi @tomhodgins , thanks a lot for the quick response. I didn't use/test the CDN release because I am writing a plugin based on the open source JWPlayer which makes me follow their practice. Please see the following dev page. I am having the issue being described in IE 11 in Windows 8.

https://dev-nlt.tc-library.org/static/lib/vendors/vialoguesplayerhtml5/vialoguesplayer/

Thank you.

**Comment by tomhodgins** [comment]
For troubleshooting I have three different questions:

1) Can you try testing using the CDN just for EQCSS and see if the error is still there?

2) I'm looking at the [vialoguesplayer](https://dev-nlt.tc-library.org/static/lib/vendors/vialoguesplayerhtml5/vialoguesplayer/) page in IE11 in windows 8 and I don't see the error. What can I do to reproduce the error you are seeing?

3) Does using this source code fix problem you're seeing? http://staticresource.com/eqcss/EQCSS.js

**Comment by eye8** [comment]
Hi, I can confirm if I use the file from the CDN (`https://cdnjs.cloudflare.com/ajax/libs/eqcss/1.3.0/EQCSS.js`) I don't have the issue. It only occurs if I include the EQCSS plugin in my webpack export. And I can also confirm the same error happens in both IE 11 (Windows 8) and Edge (Windows 10). Below is a screenshot:

https://dev-nlt.tc-library.org/static/lib/vendors/vialoguesplayerhtml5/vialoguesplayer/ie-edge-error.png

So it looks like to have something to do with webpack. Anyway, I can't use the CDN as I explained earlier. If I modify your src code so that the `domReady` callback comes after defining `throttle` (like in `http://staticresource.com/eqcss/EQCSS.js` you just gave), the IE error will be gone. Here is my exported file containing your fixed plugin (sorry you have to beautify it in order to read): 

https://dev-nlt.tc-library.org/static/lib/vendors/vialoguesplayerhtml5/bin-release/plugin.vialogues.js

Thanks for the help.

**Comment by eye8** [comment]
Hi @tomhodgins , I am wondering how's it going with this issue? Were you able to replicate my error in IE?

I am able to dig on the error a bit more today. The same error also occurs when the `EQCSS.min.js` file (v.1.3.0) is acquired via Javascript, but will not occur in the fixed version `http://staticresource.com/eqcss/EQCSS.js`. Tested in Windows 10, IE Edge. You can test with the following example code:

```
    var eqcssScript = document.createElement('script');
    eqcssScript.type = 'text/javascript';
    eqcssScript.src = 'https://cdnjs.cloudflare.com/ajax/libs/eqcss/1.3.0/EQCSS.min.js'; // error will occur
    //eqcssScript.src = 'http://staticresource.com/eqcss/EQCSS.js'; // error will not occur
    document.head.appendChild(eqcssScript);
```

Will you please release a fix? Thank you very much.

**Comment by tomhodgins** [comment]
Thanks for the troubleshooting info, I'm going to try to reproduce this and hopefully push out 1.3.1 soon with a fix :)

**Comment by tomhodgins** [comment]
Hi @eye8, I've just pushed out a tiny patch in [version 1.3.1](https://github.com/eqcss/eqcss/releases/tag/v1.3.1) for this - let me know if this fixes the problem you're having with webpack! ｡◕‿◕｡

**Comment by eye8** [comment]
@tomhodgins With v.1.3.1 everything works beautifully in IE Edge and 11. Thank you very much for the help!

**Comment by tomhodgins** [comment]
Glad to hear @eye8! Hope you have fun building with it (ᵔᴥᵔ)

**Comment by ctaepper** [comment]
@eye8 do you mind sharing your webpack config? are you using `css-loader?modules`

**Comment by eye8** [comment]
@ctaepper No I don't mind. See below:

`webpack.config.js`:

```
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

var uglifyJsOptions = {
    screwIE8: true,
    stats: true,
    compress: {
        warnings: false
    },
    mangle: {
        toplevel: true,
        eval: true,
        except: ['export', 'require']
    }
};
var pluginDependencies = [
    './src/js/utils/underscore',
    // other dependencies
    './node_modules/eqcss/EQCSS.js' // load EQCSS at the end so as to parse all dynamically inserted styles in previous scripts
];

module.exports = [
  {
    name: 'debug',
    entry: {
      'my.plugin': pluginDependencies
    },
    output: {
      path: './bin-debug',
      filename: '[name].js',
      chunkFilename: '[id].js',
      publicPath: '/'
    },
    externals: {
      jquery: 'jQuery',
      jwplayer: 'jwplayer'
    },
    module: {
      loaders: [
          {
              test: /\.html$/,
              loader: 'handlebars-loader'
          },
         {
           test: /\.css$/,
           loaders: ['css-loader']
         }
      ]
    },
    plugins: [
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery'
      }),
      new ExtractTextPlugin('[name]-[chunkhash].min.css', {
        allChunks: true
      })
    ],
    devtool: 'source-map',
    debug: true
  },
  {
    name: 'release',
    entry: {
      'my.plugin': pluginDependencies
    },
    output: {
      path: './bin-release',
      filename: '[name].js',
      chunkFilename: '[id].js',
      publicPath: '/'
    },
    externals: {
      jquery: 'jQuery',
      jwplayer: 'jwplayer'
    },
    module: {
      loaders: [
          {
              test: /\.html$/,
              loader: 'handlebars-loader'
          },
         {
           test: /\.css$/,
           loaders: ['css-loader']
         }
      ]
    },
    plugins: [
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery'
      }),
      new ExtractTextPlugin('[name]-[chunkhash].min.css', {
        allChunks: true
      }),
      new webpack.optimize.UglifyJsPlugin(uglifyJsOptions)
    ],
    watch: false,
    progress: false
  }
];
```

I also created a separate file `eqcss_styles.css` for my EQCSS styles. For example:

```
@element ".my-element" and (max-width: 580px) {
    $this .site-logo {
        margin-bottom: 10px;
    }
}
```

Note you have to use the `.css` extension otherwise there will be errors when you try to get its content. I tried `.eqcss` and it did not work.

Then, in `my.plugin.js`, you have:

```
var responsiveStyles = require('path/to/eqcss_styles.css');

define([], function() {
    // ...
    var eqcssTag = document.createElement('script');
    eqcssTag.type = 'text/eqcss';
    eqcssTag.innerHTML = responsiveStyles;
    document.head.appendChild(eqcssTag);
});
```

You don't need to require the EQCSS script in `my.plugin.js`. It doesn't export itself for us to use anyway. EQCSS will traverse the whole DOM and parse the EQCSS styles by itself once `EQCSS.js` is loaded into the DOM. However I'd recommend the EQCSS developer to consider adding the support for exporting so that we can call the `EQCSS.parse()` method as needed.

Hope it helps.

**Comment by tomhodgins** [comment]
Hi @eye8! I am not much of a Node user myself, so originally I was publishing so NPM users had a way to grab the latest version.

>  I'd recommend the EQCSS developer to consider adding the support for exporting so that we can call the EQCSS.parse() method as needed.

I was looking at Node stuff recently and wondering what/how people might want to use it better with NPM, but I don't know what I would change or add to do this! Any ideas, or examples of plugins doing what you describe here?

**Comment by eye8** [comment]
Hi @tomhodgins, I am glad you are tracking my ticket! In webpack, you need to call `module.exports = EQCSS;` in your file so that people can import your plugin into their own scripts. You probably need to refactor your code to some extent so that you can expose certain methods but not others. But it shouldn't take too much time.

A good example you can look into is [clipboard.js](https://github.com/zenorocha/clipboard.js). I used this little gem in the same project where I used yours. And it's straightforward enough so that you can see its structure easily.

My standpoint of making the previous suggestion is if we cannot call `EQCSS.parse()` ourselves, we have to load EQCSS after all styles are loaded or dynamically inserted. This is not flexible. What's more, node users probably would think your plugin does not work when they see an empty object when they import EQCSS with `require` or `define`.

**Comment by tomhodgins** [comment]
I'm not quite sure I understand so I'm going to ask some questions:

>  you need to call `module.exports = EQCSS;` in your file so that people can import your plugin into their own scripts

When people are 'importing' the plugin what is happening? Is the blob of JS being concatenated with a bunch of other JavaScript, is your build process dissecting the EQCSS plugin and rearranging the code within your app?

> You probably need to refactor your code to some extent so that you can expose certain methods but not others.

The idea with EQCSS was to be as close to the browser as possible. The idea is that as long as the JS is present in the HTML, it will run and it will behave as though the browser supports those features natively. Why would the methods inside EQCSS need to be exposed? You are already able to call things like `EQCSS.load()`, `EQCSS.throttle()` and `EQCSS.apply()` to load new styles, request a recalculation of the styles no more frequently than every 200 ms, or request a recalculation immediately. Does this do what you need?

> My standpoint of making the previous suggestion is if we cannot call EQCSS.parse() ourselves, we have to load EQCSS after all styles are loaded or dynamically inserted.

I'm not 100% sure if this works for what you need, but does running `EQCSS.load()` after those styles are applied work?

> node users probably would think your plugin does not work when they see an empty object when they import EQCSS with require or define.

Yeah that's what I was thinking when I updated the 1.4.0 release - the test command doesn't do anything, and if people are expecting it to be a javascript library instead of a frontend plugin there's nothing telling them to put the code in their JS somewhere. How could I go about notifying Node users like this or having the code do what they are expecting. Would we have to have a separate version on NPM than we would host on a CDN?

Thanks so much :) I'll check out the clipboard source, and a friend told me you might be talking about the Common JS module style, so I'll read about that too and see if what you're saying makes sense!
