### ISSUE TITLE
How to add and remove a class?

### ISSUE THREAD

**Issue by findborg** [eqcss/eqcss#42]
I was hoping that you could show me a simple example of adding and removing a class to a div.  Or,  just let me know if that is not possible. A bonus would be showing me how to catch some other events like onClick etc.   I am thinking modals, sidebars and the such.

**Comment by tomhodgins** [comment]
Hey @findborg! Thanks for checking out EQCSS!

There are a few events where EQCSS is already listening, it will run on:
- DOM Ready
- resize
- input
- click
- mousedown
- mousemove
- mouseup
- scroll

Though for scroll and mouse events we've limited how frequently EQCSS can recompute for performance reasons. You should be good to go for things where a click reveals a menu or dropdown, or something like a modal - this is exactly how we've been using it in production.

You can see these events at the bottom of the EQCSS.js file: https://github.com/eqcss/eqcss/blob/gh-pages/EQCSS.js#L904

It's also possible to recompute EQCSS on any other event as well with code like:

```
window.addEventListener('hashchange',EQCSS_apply)
```

You can also call `EQCSS_apply()` from JavaScript at any time to immediately recompute all EQCSS styles, and `EQCSS_throttle()` to recompute the styles in a throttled way: no more frequently than every 200ms (no matter how frequently you're asking for it).

As for adding or removing a class - it is possible to do via EQCSS as kind of a hack, but this would be something much better done by writing a bit of JavaScript. Suppose you had a button that toggled a class on another element, you could write something like this:

```
<button id=toggle>Toggle Div</button>
<div id=example>I'm feeling classy!</div>
<style>    
  div {
    display: none;
  }
  .show {
    display: block;
  }
</style>
<script>
  document.getElementById('toggle').addEventListener('click',
    function(){
      var example = document.getElementById('example'),
            isToggled = (example.className.indexOf('show') !== -1);
      example.className = isToggled ? '' : 'show';
    }
  )
</script>
```

In this example we have a button, an element to toggle, we have hidden the element by default using CSS, and every time a click event happens on that button it does the following:
- finds the example DIV
- checks whether it is currently toggled or not by looking for class="show"
- adds or removes the class="show" class

I hope that answers all your questions, there are dozens of demos you can read, play around with, even fork or use over on Codepen covering many many different use cases, including things like modals!

http://codepen.io/search/pens?q=Eqcss&limit=all&order=popularity&depth=everything&show_forks=false

Let me know if you have any further questions, and also check out the EQCSS Gitter chat for more help like this :)

http://gitter.im/eqcss/eqcss

**Comment by findborg** [comment]
@tomhodgins  Thank you very much for taking the time to explain.  I am currently starting to learn this and a project called vue.js.  I am building web components so that I can rebuild my site.  I am a self taught guy so I always appreciate it when someone makes the extra effort to explain something or how it works.  FYI,  I have eqcss working great on a skeleton stack using browserfy - vue.js - eqcss - and  stylus.  Getting stylus to play nice was a little bit of a trick.  It kept changing the word "and"  to "&&".  It took me two nights to find the problem.  I am sure you know the feeling.   I fixed the problem by escaping the word like this \a\n\d.  Now I can use stylus vars in eqcss and ready to rock and roll!

**Comment by tomhodgins** [comment]
@findborg glad my explanation helped! I've only experimented with Stylus with EQCSS, and I haven't used Vue.js on anything yet so I'm very curious to see what you build with it!

If you want to add EQCSS styles to your project and don't need to take advantage of Stylus features you can always split your styles between Stylus-powered CSS + media queries, and put your element queries in a separate CSS file that isn't compiled, and you're also able to load styles from a custom script type of `text/eqcss` like this:

```
<script src=styles.eqcss type=text/eqcss></script>
```

Good luck <s>and</s> && happy hacking! :)

**Comment by findborg** [comment]
You are right.  As a matter of fact,  in case others read this.  When using vue.js with the vue-loader I can build components using a single or multiple files as you described.  However,  I like the single page because everything is right in front of you like this
template   /template
script       /script
style       /style
Here is the cool part:  This setup actually worked just fine for adding eqcss But,  I could not use stylus vars.
template   /template
script       /script
style lang="stylus"       /style
style type="text/eqcss"  /style

I was real surprised that it did not throw an error when compiling the js modules,  but it works.

[This is what it looks like working with stylus](https://github.com/ExoTypography-Elements/earth-skeleton/blob/master/src/skeleton/Skeleton.vue)

**Comment by findborg** [comment]
@tomhodgins   BTW,  Eqcss + Vue.js = Match made in heaven.
