### ISSUE TITLE
Is there a way to load the eqcss inside a js file?

### ISSUE THREAD

**Issue by scooterlord** [eqcss/eqcss#44]
Hello there, your plugin is fantastic, the best around! Keep up the good work and good luck in getting this standardized.

I was wondering if there is an alternative way of initializing eqcss; I am working on a project and need to provide templates, so inline code is out of the question, and there are requirements just for 1 js and 1 css file. 

It sounds more likely that the code can be triggered from within a js file rather than a css file. Can this be done?

Thanks for your time and efforts!

**Comment by tomhodgins** [comment]
Hey @scooterlord! Thanks for your interest. The simplest way to store your EQCSS-enabled element queries would be to place them in your single CSS file. EQCSS it not designed to execute styles from inside JavaScript, so the only way I could think of storing them in JavaScript would be to store CSS, create a style element, and append it to the page like this:

``` javascript
var tag = document.createElement('style'),
    css = "@element 'body' { $this { background: red } }"
tag.innerHTML = css
document.body.appendChild(tag)
```

But that would have no advantage over putting the styles inside your CSS file, and it would be harder to edit and work with after it's packaged up that way.

Other than in an external .css file or `<style>` tag, the third way you can load EQCSS (and this provides future compatibility for all those worried EQCSS syntac may someday collide with the CSS of the future) is by loading EQCSS code as a `<script>` with the type `<script type=text/eqcss src=styles.eqcss></script>`, but this would lead you to having 1 js file, 1 css file, and 1 eqcss file.

Does that answer your question?

**Comment by scooterlord** [comment]
@tomhodgins Thanks for your fast reply - although it took me too much to respond back :)

..looks like I was doing something terribly wrong. I was under the impression that it could only be loaded inside an html as an INLINE style or in the script. It is not clearly stated that it can be loaded in an external file, so I would suggest you add it - might be obvious but...

...this, along with the fact that I put the css inside a sass and forgot to put an empty space, the css wasn't processed properly, thus, no output, thus wasn't working. 

Thanks !
