### ISSUE TITLE
Scoping example breaks site

### ISSUE THREAD

**Issue by TheDiscoMole** [eqcss/eqcss#51]
Hey this projects awesome first of all, but I am having an issue with the feature that i want the most.

adding this (or any variation of this): 

```
@element 'body' {
  $this,
  $this *,
  $this :before,
  $this :after {
    all: initial !important;
  }
}
```

at the end of a page load to the styles in the header and running `EQCSS.load()` breaks the entire website formatting into raw text. Doesn't matter which site i inject this into, it wrecks my hopes and dreams.

EDIT: or is this my mistake and have i misinterpreted this piece of code for `iframe` like wrapping when it really just disconnects parts that should be connected?????

**Comment by tomhodgins** [comment]
It sounds to me like it's doing _exactly_ what it's supposed to :D

The rule you're using could be explained in prose like this:

> If there is a `<body>` tag present, on the `<body>` tag, all of its children, and `body:before` and `body:after`, reset _all_ properties to their initial value. And force it if it doesn't want to.

It _should_ take HTML, even unstyled HTML with just the default styles set by the browser that might look like this before:

![screen shot 2017-03-01 at 12 46 52 pm](https://cloud.githubusercontent.com/assets/955601/23473184/497f8746-fe7d-11e6-8096-e0225485bb2e.png)

And reset all of those styles to give you something that looks like this:

![screen shot 2017-03-01 at 12 47 12 pm](https://cloud.githubusercontent.com/assets/955601/23473202/54367a32-fe7d-11e6-8fb9-d157f55864d1.png)

If that's what you're seeing, it's _working_! You can do the exact same thing with the following CSS:

```css
* {
  all: initial !important;
}
```

Which is actually what I used to make the screenshot above. I'm assuming you're interested in using the style scoping to 'reset' an element and its children, so here's an example of adding an element into that last demo called `<section class=scoped-example>`, using a reset just on that element and its children (not the entire document) and then setting new styles for elements within that scope :D Hopefully this makes more sense:

```html
<h1>Basic CSS Test</h1>
<h2>Testing <code><a href=https://gist.github.com/tomhodgins/e330ec1826d1cde2b8b0>basic.css</a></code></h2>
<p><strong>Lorem ipsum dolor sit amet,</strong> consectetur adipisicing elit, <em>sed do eiusmod tempor incididunt</em> ut labore et dolore magna aliqua. <u>Ut enim ad minim veniam</u>, quis nostrud exercitation ullamco <a href=#>laboris nisi ut aliquip</a> ex ea commodo consequat. Duis aute irure dolor in reprehenderit in <code>voluptate</code> velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<section class="scoped-example">
  <h2>Scoped Styles Example</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</section>

<blockquote>
<p><q>This is a blockquote</q></p>
<footer>First Last</footer>
</blockquote>
<h2>List Test</h2>
<ul>
<li>list item
<li>list item with <a href=#>a link</a>
<li>list item
</ul>
<ol>
<li>list item
<li>list item with <a href=#>a link</a>
<li>list item
</ol>
<h4>Button Test</h4>
<a href=# data-button>default button</a>
<a href=# data-button="blue">.blue button</a>
<a href=# data-button="green">.green button</a>
<a href=# data-button="red">.red button</a>
<a href=# data-button="grey">.grey button</a>
<a href=# data-button="outline">.outline button</a>
<br>
<a href=# data-button disabled>default button</a>
<a href=# data-button="blue" class="disabled">.blue button</a>
<a href=# data-button="green" hidden>.green button</a>
<a href=# data-button="red" disabled>.red button</a>
<a href=# data-button="grey" class="disabled">.grey button</a>
<a href=# data-button="outline" hidden>.outline button</a>
<pre>&lt;script>alert('I LOVE ALERTS!')&lt;/script></pre>
<h1>This is an &lt;H1&gt; Headline</h1>
<hr>
<h2>This is an &lt;H2&gt; Headline</h2>
<h3>This is an &lt;H3&gt; Headline</h3>
<h4>This is an &lt;H4&gt; Headline</h4>
<h5>This is an &lt;H5&gt; Headline</h5>
<h6>This is an &lt;H6&gt; Headline</h6>


<style>
  * {
    box-sizing: border-box;
  }
  /* on-page styles */
  body {
    font-family: monospace;
    background: black;
    color: lime;
  }
  
  @element '.scoped-example' {
    $this,
    $this * {
      all: initial;
    }
    $this {
      display: block;
      font-size: 10pt;
      padding: 1em;
      font-family: sans-serif;
      background: gold;
    }
    $this h2 {
      display: block;
      font-size: 24pt;
      margin: 0 0 .5em 0;
    }
  }
</style>

<!--[if lt IE 9]><script src=http://elementqueries.com/EQCSS-polyfills.js></script><![endif]-->
<script src=http://elementqueries.com/EQCSS.js></script>
```

![screen shot 2017-03-01 at 12 53 52 pm](https://cloud.githubusercontent.com/assets/955601/23473412/27ae3db4-fe7e-11e6-9807-72e84395b662.png)

**Comment by TheDiscoMole** [comment]
wow thank so much for the amazingly detailed reply so quickly. Yea i realised that my interpretation of the function of the code may have been flawed and that it would behave as you explained instead. If I may enquire, though i get this is not the right place to do so, is there anything i can do to retroactively add eqcss to an existing webpage such that all its functionality remains normal but i can treat certain elements with `iframe` like seperate viewport-ish behaviour?

**Comment by tomhodgins** [comment]
Hi @TheDiscoMole! When you say 'iframe-like viewportish behaviour' do you mean in regards to something like `vw` and `vh` units relative to the width and height of that iframe when embedded into another HTML document? If you're just looking for containment and sizing purposes EQCSS can help out, but if for some reason you need that element to think of itself as a separate document for JS you'd need something like an iFrame.

Are you able to post a live example of what you're looking for, or a code sample of what you want? I can only guess :D

My guess is that if you have a website with its own styles, and you wanted to be certain that the element and styles you add to it won't affect the page outside of that element, using EQCSS could be done like so:

```html
<div class="new_widget">
  <h2>Widget Headline</h2>
  <p>Example paragraph inside the widget</p>
</div>
<style>
  @element '.new_widget' {
    $this {
      color: red;
      background: lime;
    }
  }
</style>
<script src=http://elementqueries.com/EQCSS.js></script>
```

Now if you're looking for 'viewport-size-aware' sizing like you would get with `vw` or `vh` units, EQCSS does support some new element-based units: `ew`, `eh`, `emin`, and `emax`. You could based the font-size of the elements inside your widget on the width of the widget itself. This is a different way that EQCSS could be used to provide iframe-like styling to elements on a page:

```html
<div class="new_widget">
  <h2>Widget Headline</h2>
  <p>Example paragraph inside the widget</p>
</div>
<style>
  @element '.new_widget' {
    $this {
      color: red;
      background: lime;
    }
    $this h2 {
      margin: 0;
      font-size: 10ew;
    }
    $this p {
      font-size: 3ew;
    }
  }
</style>
<script src=http://elementqueries.com/EQCSS.js></script>
```

As you can see here, the `10ew` and `3ew` sizes are based on the width of `.new_widget`, and refer to 10% of `.new_widget`'s width and 3% of `.new_widget`'s width how it shows up on the page at any given time. Is this the sort of functionality you're looking for?

You can read more about the element-based units here: https://tomhodgins.github.io/element-queries-spec/element-queries.html#element-based-units

**Comment by TheDiscoMole** [comment]
Basically I am writing a browser extension and need it to be able to wrap any page it opens in such a way that there is an empty side-bar on the right side equal to 33% o the page size. My original code looked like this:

manifest.json:

```
{
    "name": "test",
    "version": "1",
    "manifest_version": 2,
    
    "content_scripts":
    [
        {
            "js": ["EQCSS.js", "content_script.js"],
            "matches": ["*://*/*"],
            "run_at": "document_end"
        }
    ]
}
```

content_script.js:

```
window.onload = function() {
    
    var wrapper = document.createElement('div');
    
    wrapper.id = 'wrapper';
    wrapper.style.height = "100%";
    wrapper.style.width = "67%";
    wrapper.style.position = "absolute";
    
    wrapper.innerHTML = document.body.innerHTML;
    document.body.innerHTML = wrapper.outerHTML;
    
    //var eqcss = document.createElement('style');
    
    //eqcss.type = 'text/eqcss';
    //eqcss.innerHTML = "@element '#rapper' {" +
    //   "$this," +
    //   "$this *," +
    //   "$this :before," +
    //   "$this :after {" +
    //       "all: initial !important;" +
    //    "}" +
    //"}";
    
    //document.head.appendChild(eqcss);
    
    //EQCSS.load();
};
```

But on many websites this formatting is just really awkward and i wanted to use eqcss to wrap the entire page so i can squeeze it like this and do my sidebar stuff without worries.

**Comment by tomhodgins** [comment]
To be honest, I'm not sure if you'll be able to do that, even with EQCSS! If you're wanting to squish a document that uses `@media` queries, and add a 33% wide sidebar into the same browser viewport at the same time you'll need to have the browser _think_ the page is actually the width it's showing up (66% of the browser) so when _it_ is 500px wide (and the browser is actually 750px wide) the rule for `@media (min-width: 500px) {}` would kick in.

I tried just now to see if I could force the `<html>` element to be narrower than the viewport, and what would happen - but the first page I tried it on used `position:fixed` to position the layout, so it was already detached from the `<html>` element's dimensions. For that reason I'm not sure you'd be able to do anything _within_ an HTML document to squeeze it like this.

Another way to explore that might work though - are you able to add an iframe _of the current page_ inside the viewport, and put your 33% sidebar next to that? If you are able to capture the entire active page in an iframe I think the width, media queries, and things like my `position: fixed` layout would respond as you want. The question with putting stuff in iframes is always: can you get to it from where you need, and can the code inside reach the outside if you need to. If you're able (via browser extensions) to add your own JS to the page inside the iframe I think you might be able to make it 'talk' to the page holding it :D

I'm very curious to see what you do with this! Is it a chrome extension?

**Comment by TheDiscoMole** [comment]
Unfortunately framing websites in iframes even you are actually on that website anyway is against many TOS agreements. Thanks a bunch for the attempted help and yes `position: fixed` annoyances are the main reason i looked up eqcss in the first place haha. If i figure anything out i promise to post back here :)

**Comment by tomhodgins** [comment]
The closest I got today was: what if you shrink the `html` element using `scale()` and then push the sidebar to what would normally be out of sight off the edge of the viewport. It's not perfect, but here's an example. The downside of a technique like this is it's shrinking the fonts and the site from `1` to `.66` scale :/

```html
<h1>Hello There!</h1>

<aside></aside>

<style>
  html {
    transform: scale(.66);
    height: 152vh;
    transform-origin: left top;
    background: red;
  }
  body {
    height: 100%;
    margin: 0;
  }
  aside {
    width: calc(33.33vw * 1.5);
    position: fixed;
    left: 100vw;
    top: 0;
    height: 100%;
    background: lime;
  }
</style>
```

Maybe it helps you think of a different approach though!

**Comment by tomhodgins** [comment]
Keep me posted on your browser plugin progress, I'm curious to see what you come up with :) I'll close this issue for now unless there are further EQCSS-related issues on it.
