### ISSUE TITLE
codepens not working

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [eqcss/eqcss#56]
in the codepen examples im getting a 
```
Failed to load resource: net::ERR_INSECURE_RESPONSE
```
for EQCSS.js library

eg on this example https://codepen.io/tomhodgins/pen/xwRNpm

**Comment by tomhodgins** [comment]
Hi! Thanks for pointing this out - I created that demo on Codepen at a time when Codepen wasn't HTTPS and the file I linked to was over HTTP. I've updated this demo (by replacing it with a link that uses HTTPS) so this should work now :D Thanks for letting me know!
