### ISSUE TITLE
bloated style tags in <head>

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [eqcss/eqcss#57]
Im testing out EQCSS and for some reason this rule
```scss
@element '.ber-new' {
	eq_this: {
		max-height: eval('parentNode.offsetHeight+"px"');
	}
}
```
is resulting in this style tag in the head
```html
<style id="data-eqcss-0-0" data-eqcss-read="true"> 
[data-eqcss-0-0]-max-height: 286px; } 
#about { color: #E21C3C; padding: 2rem; margin-top: 5rem; } #about p.align-right { text-align: right; } #about .top img { float: right; display: inline-block; max-width: 200px; margin-left: 2rem; } #about .rest { max-width: 100%; margin-left: auto; margin-right: auto; } #about .rest:after { content: " "; display: block; clear: both; } #about .rest .left { width: 100%; float: left; margin-right: 10%; } @media (min-width: 1200px) { #about .rest .left { width: 31.25%; float: left; margin-right: 3.125%; } 
</style>
```
the only bit that is meant to be in there is the max-height: 286px; bit, but its pulling in CSS from subsquent style rules outside of the @element block

**Comment by matthewjumpsoffbuildings** [comment]
also even though the eval() is correctly calculated, and the .ber-new element im targeting gets the `data-eqcss-0-0` attribute added, its not applying the styles?

**Comment by tomhodgins** [comment]
Hi @matthewjumpsoffbuildings! I notice in your original source you have a `:` after the `eq_this` which I'm guessing is the source of your troubles here. It's hard to say without seeing the actual code you're working with.

If I remove the `:` and add an HTML element it does appear to be applying the style to the element:

```html
<div class=ber-new>Hi</div>
<style>
  @element '.ber-new' {
    eq_this {
      max-height: eval('parentNode.offsetHeight+"px"');
      background: lime;
    }
  }
</style>
<script src=http://elementqueries.com/EQCSS.js></script>
```

Does that rule work for you?

**Comment by matthewjumpsoffbuildings** [comment]
oh damn that was it. i didnt even notice it since my SCSS hilighter in atom has "eq_this" as a big red block :/

thanks. can i delete this issue, or can you?

**Comment by tomhodgins** [comment]
Glad that solved it! :)
