### ISSUE TITLE
[Safari|IE|Firefox] Performance Issues

### ISSUE THREAD

**Issue by gisu** [eqcss/eqcss#65]
Hi, in the last days i builded a onepager with EQCSS. Two Sliders, one Accordion and Smoot Scrolling Anchor Navigation. Everything was fine on Chrome.

But on IE, Firefox and especially with Safari I had many Performancedrops, if one of the animations wants to start. The reaction after click is delayed and in the animation phase itself there is a short stop in the middle.

In total there were 15 EQCSS Conditions working in the background. The only browser that did not bother you was Chrome. As I said the whole falls on the other browsers synonymous then only properly when you animate elements.

I am testweise again changed back to the CQ-Prolyfill (https://github.com/ausi/cq-prolyfill)  there it runs without problems, but also stop fewer options.

**Comment by tomhodgins** [comment]
Oh no! Sorry you're having a hard time with it @gisu

Do you have an example of the EQCSS-powered version that had the performance issues - I'd love to have a peek and see where they might be coming from, either if there's a way it could be refactored to run more smoothly or if this exposes some performance issues with the plugin we could improve!

**Comment by tomhodgins** [comment]
Hi @gisu! Any update on this? I'd love to have a peek at code that can reproduce the problem to see what can be done about it :D

**Comment by gisu** [comment]
Ah sorry for the late reply. But an example I have unfortunately no longer. The site where I have integrated EQCSS is not yet public and now runs the CQ-Prolyfill.

I try to put the days but once a similar page, where you will see the problems then.
