### ISSUE TITLE
Q: Could EQCSS be used as a replacement for CSS Regions?

### ISSUE THREAD

**Issue by glennphilp** [eqcss/eqcss#67]
Is it possible to use EQCSS to create flow from one container into multiple containers? Currently, I have been using a [CSS Regions Polyfill](https://github.com/FremyCompany/css-regions-polyfill), which works okay, but I was hoping to find a better solution until browsers start supporting the W3C CSS Regions.

**Comment by tomhodgins** [comment]
Hey @glennphilp! CSS regions are pretty interesting, but I can't see how you would be able to do anything for emulating them with EQCSS that wouldn't be more straightforward and better performing to do using JavaScript :/ We have support for `min-lines` and `max-lines` but even that is proving tricky to compute in all cases.

I think the closest to a region-based thing I've done with EQCSS is putting queries on an element based on the number of columns the text is split into: http://codepen.io/tomhodgins/pen/WRggZa

What kind of stuff do you do (or want to do) with CSS regions?

**Comment by glennphilp** [comment]
My goal is to allow designers to be artist, while content contributors/writers be able to make magic from their words. The challenge for developers is to marry the designers art with the writers magic and keeping it simple for them to input. Most of the time this requires lengthy documentation, training, and hand-coding.

If you are using Firefox, Safari, or Chrome you can see an [example](http://codepen.io/glennphilp/pen/LyjbMz) of using a CSS regions polyfill with Flex and Grid. Edge is working to support the new Grid syntax soon.

Since Adobe first introduced the concept of magazine layouts for the web it has caught my interest. The ability to wrap text around images and create flow without inhibiting the designers and writers. Although Chrome has dropped support for CSS regions, Safari does support them and IE/Edge has support using iframes. And I hope the Chrome dev team will see the power of regions in the future.

More reading on Regions:
- http://webplatform.adobe.com/regions/
- https://www.html5rocks.com/en/tutorials/regions/adobe/
- http://blogs.adobe.com/webplatform/category/features/css-regions/
