### ISSUE TITLE
Problem with Version 1.7.0

### ISSUE THREAD

**Issue by MasterB** [eqcss/eqcss#68]
Version 1.6.0 works.

The new version 1.7.0 does not work on Firefox 53.0 on Mac. 
Error: TypeError: css_code is undefined (EQCSS-170.js:1124:13)

**Comment by tomhodgins** [comment]
Hi @MasterB, The new version of EQCSS has been tested with Firefox, I have it running in Firefox v53 on OS X right now and the http://elementqueries.com homepage works, and all 32/32 tests on http://elementqueries.com/tests/ are working without any errors in the console.

Are you able to provide a link to where this isn't working, or a test case where I can reproduce this on jsfiddle or codepen? I'd love to have a peek at what you're seeing and see if I can figure out what's happening :)

![ff53](https://cloud.githubusercontent.com/assets/955601/25707358/478ef258-30b1-11e7-8fa2-d1d63dfd61d5.png)

**Comment by MasterB** [comment]
Ok, some strange thing happend!

With Firefox:
Over my local Apache http://localhost/EQCSS/index-1.7.htm it does not work.
Same code called over file:///var/www/html/EQCSS/index-1.7.htm works fine.
Same code works over my production webserver.
(with index-1.6.htm works perfect on any cases)

Any idea?

see my code.

[EQCSS.zip](https://github.com/eqcss/eqcss/files/978162/EQCSS.zip)

Error printsceen on firefox:
![bildschirmfoto 2017-05-05 um 07 40 25](https://cloud.githubusercontent.com/assets/763745/25734712/274a7c28-3166-11e7-9ff7-8009c7d951e5.png)

correct behavior:
![bildschirmfoto 2017-05-05 um 07 48 15](https://cloud.githubusercontent.com/assets/763745/25734873/57ba71c8-3167-11e7-95b8-469d9a159cfe.png)

**Comment by tomhodgins** [comment]
Hi @MasterB! Thanks for the test files. When I download them and view them from my computer (just via `file:/`) the styles do show up for me in Firefox in both the 1.6 and 1.7 versions.

I do see an error message in both though:

> EQCSS-1.6.0.js:137 XMLHttpRequest cannot load file:///Users/tomhodgins/Desktop/masterb/main.css. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

Though they still render fine. If I upload the files I you gave me to my web server here: http://staticresource.com/masterb/ they show up without any errors.

I'm not able to reproduce the problem you're seeing with `css_code` :/ Do you have any other ideas for troubleshooting how I might be able to reproduce what you're seeing here?

![screen shot 2017-05-05 at 1 54 49 am](https://cloud.githubusercontent.com/assets/955601/25735035/5369a750-3136-11e7-88f1-889992623f76.png)

**Comment by MasterB** [comment]
Hey I found a solution for my problem:
I used a normalize css from github.com/necolas/normalize.css (normalize.css v6.0.0)
now I've updated to (normalize.css v7.0.0) an now it works with EQCSS version 1.7.0 without any problems.
For me its ok now. 
Thanks @tomhodgins  for your support.

**Comment by tomhodgins** [comment]
Thanks for the update @MasterB, did you figure out why there was a conflict or what we could do about it? It seems strange that the content of a file could cause a problem like this.
