### ISSUE TITLE
EQCSS + Development mode

### ISSUE THREAD

**Issue by justincorrigible** [eqcss/eqcss#74]
Is it only me (maybe I'm doing something wrong), but it seems like adding EQCSS to my app has messed up the way CSS is loaded in the browser while using webpack dev-server.
Formerly, Chrome would offer the chance to make in-browser changes (i.e. changing font size, colour, etc. on the go, and saving directly from the browser). After adding this awesome plugin, the styles seem to be added directly to the html as script references to a blob, which somehow disables chrome from modifying them. It's odd, but may be an expected behaviour I'm simply not aware of.

However, I'd like to be able to continue making changes directly through the browser while in dev mode.
(also leveraging hot reloading).
Any ideas?

**Comment by tomhodgins** [comment]
Hey @hallaathrad! I'm so glad you're checking out EQCSS and having fun with it. I don't think EQCSS running in the browser would be compatible with editing and saving your files in the browser for a few reasons:

- EQCSS adds attributes to the tags in the document that styles apply to: when an EQCSS query matches an element, you'll notice it add an attribute like `data-eqcss-0-0` to an element, or maybe `data-eqcss-parent-0-0` and other attributes for the elements close to it. If there's any chance that saving from Chrome's Dev Tools would save these attributes into your HTML you're going to have a bad time working with it later.

- EQCSS outputs 1 new `<style>` tag in the document for each query it's watching. If the query doesn't apply, this style tag has no content, but any time a query applies each of these plugin-generated style tags will get filled with CSS written for the custom attributes I mentioned before - ensuring the right styles get applied to the right elements at the right time

- Further, I think if you're editing CSS styles using Inspect Element, and tweaking the CSS that's applying to these elements - none of the tools you are using (the browser, your saving plugin) are aware that the CSS applied by the EQCSS plugin is coming from the EQCSS plugin. The CSS it applies only exists in the document at that moment in time. If you were to edit any CSS styles coming from the EQCSS plugin, your dev tools wouldn't have any way of saving the changes that you make in Inspect Element back to the original EQCSS

So I'm sorry if that throws a wrench in your editing workflow :/ I have a few other plugins I use for similar things, but they all function in a similar way: marking up matching tags with custom attributes, creating new <style> tags, outputting custom CSS written for those tags, so I'm pretty sure this entire class of CSS plugins would be incompatible with the live-editing-in-browser workflow you are using.

**Comment by justincorrigible** [comment]
Oh thanks for that thorough explanation. No complaints here as the plugin is pretty cool (they really need to add Element Queries to the standard), just making sure it was not something I was doing wrong; yet I did have a gut feeling the missing functionality was by design.

I do wonder if maybe I am applying EQCSS at a too broad scope, and maybe it's observing far too many things that have little to nothing to do with the intended element to be queried. Will run some experiments and see if I can update this issue with some workarounds. Meanwhile, closing. Thanks for your quick response :+1:

**Comment by justincorrigible** [comment]
Turns out the issue seems to have been caused at some point when I was adding the EQCSS plugin (i.e. not due to the plugin, but own app's environment), in which I'd removed the publicPath from htmlWebpack, and from webpack.output. Cannot remember why exactly it was giving me trouble while adding EQCSS, but the issue has been solved. Happy day.
