### ISSUE TITLE
Making EQCSS Work

### ISSUE THREAD

**Issue by ghost** [eqcss/eqcss#75]
I'm using Django so all my front-end assets are loaded from a static file folder. First, I try to load the script from `EQCSS.js` . Then I load my custom custom styles from `respond.eqcss` which contains element queries.

    <script src = "{% static 'js/EQCSS.js' %}"></script>

    <script type = "text/eqcss" src = "{% static 'css/respond.eqcss' %}"></script>

For whatever reason, this isn't working at all. I have valid element queries, and I believe I've loaded my styles properly, but I can't seem to determine why the styles aren't taking affect. Does anyone have any ideas?

**Comment by tomhodgins** [comment]
Hi Malik, thanks for checking out EQCSS!

From what I can see, as long as those file paths resolve in your HTML everything looks linked in correctly - the EQCSS.js code just needs to be present in the document somewhere, styles in EQCSS syntax can be loaded into the document inside a `<style>`, via a `<link>`, or `<script type=text/eqcss>` as you've done here.

To troubleshoot what's happening let's inspect what's going on on your page. The first thing we can do is check if the EQCSS.js is successfully running, then we can check to see what styles it has loaded and finally we can inspect the document to see if or why loaded styles aren't applying the way we expect.

## Checking if EQCSS is loaded

![eqcss-defined](https://user-images.githubusercontent.com/955601/30251914-502143ee-9637-11e7-90be-f76ce19440ab.gif)

- open the JavaScript console in your browser
- type `EQCSS` and hit the Enter key
- if the EQCSS plugin _is not_ running you will see an error
- if EQCSS _is loaded_ it will return the current plugin object in the console

## Checking what styles the plugin has loaded

![eqcss-loaded](https://user-images.githubusercontent.com/955601/30251917-5b91485a-9637-11e7-95c5-d7b7d38419f4.gif)

- open the JavaScript console in your browser
- type `EQCSS.data` and hit the Enter key
- all queries the EQCSS plugin has loaded will show up as entries in this array
- if it returns `[] (0)` that means the plugin is running, but no styles have been recognized


## Looking for plugin-set attributes in the DOM

![eqcss-read](https://user-images.githubusercontent.com/955601/30251946-d4eff926-9637-11e7-9319-2e1ef8ce4bb8.gif)

- Open Inspect Element in your dev tools and look at the current HTML in the browser
- search for 'data-eqcss-read' to find stylesheets the EQCSS plugin has tried to extract queries from
- search for `data-eqcss-` and look for attributes like `data-eqcss-x-x`, `data-eqcss-x-x-parent` where `x` are numbers starting at 0 and increasing for the current query count and element count
- if you were investigating which elements the third query in `EQCSS.data` was affecting, you could find the elements affected by `EQCSS.data[3]` by searching the DOM for attributes starting with `data-eqcss-3-`

Hopefully using the troubleshooting ideas above you can see what's going on here! Do you have an example of what you're seeing online that I could take a look at?

**Comment by ghost** [comment]
It is definitely is loading according to the checks you've posted. However, there is no actual change.

![image](https://user-images.githubusercontent.com/31360324/30252682-e9ca646e-9644-11e7-997d-c658afe3fa0f.png)

**Comment by ghost** [comment]
Unfortunately, I don't have anything online because deployment is going to be a whole other issue with my host. But if you'd be willing to join a Team Viewer or any other private screen share, I'd be more than willing to share my workflow so we can get to the bottom of this.

**Comment by ghost** [comment]
Truth be told, I've tried EQCSS in the past in front-end websites with no back-end at all. Never got it to work.

**Comment by tomhodgins** [comment]
It looks like you've got `content` as a selector which would select a `<content>` tag, I wonder if that's part of the problem, there's no standard `<content>` tag in HTML so you're kind of at the mercy of whatever each browser decides to do when they encounter a non-standard tag. In my browser it seems to create an element like a `<span>`, it's `display: inline` by default which means unless I change it to `display:block` it's not going to behave like a `<div>`.

If we try a streamlined test case - can you verify if this works? I've tried to replicate what I think a bit of your HTML markup might look like, and copied in the first `@element` query from your screenshot and viewing this code in the browser works for me - do you see the background of this element as green when it's wider than 992px?

```html
<content><p>I am a <code>&lt;content&gt;</code> tag</p></content>

<style>
  /* the made-up <content> tag is behaving like inline by default, */
  /* setting display to block makes it behave like a <div> */
  content {
    display: block;
  }

  @element content and (min-width: 992px) {
    content {
      background: green;
    }
    p {
      font-size: 14px;
      line-height: 28px;
    }
  }
</style>

<script src=http://elementqueries.com/EQCSS.js></script>
```

Is this what you see? Here's the same code as a CodePen too: https://codepen.io/tomhodgins/pen/ayeMbv

![testing](https://user-images.githubusercontent.com/955601/30252839-5e9ce1d4-9647-11e7-833c-6f4c15e311b3.gif)

It should be easy to get working on the frontend - you can include the code of EQCSS.js inside `<script>` tags right in your HTML, you can include it anywhere in any JS file you're loading into your website, or even link to a CDN-hosted copy of it like `<script src="https://cdnjs.cloudflare.com/ajax/libs/eqcss/1.7.0/EQCSS.min.js"></script>` and it will run. A small HTML5 document with EQCSS enabled might look something like this:

```html
<!DOCTYPE html>
<title>Small EQCSS-enabled HTML5 template</title>
<style>
  @element html {
    $this {
      background: lime;
    }
  }
</style>
<script src=http://elementqueries.com/EQCSS.js></script>
```

If you load that as an HTML file in the browser and the background is green, EQCSS is running :D

**Comment by ghost** [comment]
I changed it to `.content` and it worked beautifully. My apologies I guess I thought it selected via class name.

**Comment by tomhodgins** [comment]
Oh good! I'm glad you got this working in the end :) Let me know if you have any other support questions in the future :D
