### ISSUE TITLE
All demos seem to be broken

### ISSUE THREAD

**Issue by TylerBarnes** [eqcss/eqcss#80]
I get `EQCSS.min.js:37 Uncaught SyntaxError: Unexpected end of input` and the demo pages don't seem to be doing anything.

**Comment by tomhodgins** [comment]
Ah great catch! Thanks for letting me know, it was just a few characters missing from the end of the minified file, I've just pushed out v1.7.2 as a fix to this. Thank you @tyler-barnes <3

![diff](https://user-images.githubusercontent.com/955601/33235280-13f60b2c-d203-11e7-837a-9df2c2d48f03.png)

These demos should all be working again now!

**Comment by TylerBarnes** [comment]
Awesome, they look great now!
