### ISSUE TITLE
<script src=EQCSS.js></script>

### ISSUE THREAD

**Issue by tobireif** [eqcss/eqcss#81]
Does this line from the README
```
<script src=EQCSS.js></script>
```
require quotes?

**Comment by tobireif** [comment]
(I added quotes in my code.)

**Comment by tomhodgins** [comment]
Hi @tobireif, good question. It's totally okay to quote attribute values, and in certain situations (like when they don't contain spaces, `=` equal signs, etc) you can also leave attribute values unquoted. 

In this case both with and without quotes are equivalent, so they are both correct, I just tend to do the shorter one :D Feel free to wrap your attribute values in quotes - doing that can never be wrong!
