### ISSUE TITLE
Option for disabling throttling

### ISSUE THREAD

**Issue by tobireif** [eqcss/eqcss#82]
Perhaps there is or could be an option for disabling throttling?

**Comment by tomhodgins** [comment]
Hi @tobireif, there currently isn't an option for disabling throttling, but you are able to invoke `EQCSS.throttle()` or `EQCSS.apply()` directly on any events you like, which gives you a lot of flexibility as to when the styles will reprocess.

For example, suppose you have a `<div id=scrollDemo>` and you want to use a `scroll` feature like `min-scroll-y`, normally EQCSS might not reprocess enough to trigger that breakpoint when it should, so we can add event listeners to JavaScript like this:

```js
let demo = document.querySelector('#scrollDemo')

demo.addEventListener('scroll', EQCSS.apply)
```

Then, every time the `<div id=scrollDemo>` scroll event fires, EQCSS is going to be recalculated. Does that make sense?

**Comment by tobireif** [comment]
Yep, in the meantime I added this:
```

EQCSS.apply();

buttons.forEach(function(button) {
  button.addEventListener("click", function(){
    EQCSS.apply();
  });
});

[
  "DOMContentLoaded", "load", "resize", "orientationchange"
].forEach(function(e) {
  window.addEventListener(e, function(){
    EQCSS.apply();
  });
});
```
