### ISSUE TITLE
ResizeObserver

### ISSUE THREAD

**Issue by tobireif** [eqcss/eqcss#83]
Is ResizeObserver something to consider for future versions of the EQCSS lib?

**Comment by tomhodgins** [comment]
Hi @tobireif! I think ResizeObserver will forever fall outside of scope for EQCSS's browser support. Currently all features are working IE8+. It should be easy to build new plugins that take advantage of ResizeObserver though, here's a basic element queries plugin using Resize Observer: https://codepen.io/tomhodgins/pen/MERNEY
